apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      containers:
      - name: backend
        image: docker.io/semyonnadutkin/speakflow-backend:latest
        imagePullPolicy: Always

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true

        volumeMounts:
        - name: recordings
          mountPath: /recordings
        - name: tmp
          mountPath: /tmp

        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 500m

        env:
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: deepseek_api_key

        - name: JWT_ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: jwt_algorithm

        - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: jwt_access_token_expire_min

        - name: JWT_REFRESH_TOKEN_EXPIRE_DAYS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: jwt_refresh_token_expire_days

        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt_secret_key

        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: database

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: user

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password

        ports:
        - containerPort: 8000

      volumes:
      - name: recordings
        persistentVolumeClaim:
          claimName: recordings-pvc
      - name: tmp
        emptyDir: {}

      restartPolicy: Always
