---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: default
spec:
  encryptedData:
    jwt_secret_key: AgCjm4A67CWiMFARdgYgzQgqw728t1HwCJ6iIYp7cHZuBxjk78VvmDKupdFKOywVcmF/r6ArG/XjnPDBSMIvkoAULLZiaW4m32yB2nSsyz8cjrlymqR+rlfNeS4iGWY6X3rpFz+5iSpk10hw0q0181jmPf+cWN+tromN+EcrtVDhxfnQyQ89mBHnhOHzwpw2JCJ4AD6eoAtyCrNhYLeRZI9tNAbNRtIMIJH38N90HeROaMdBLv4cwml+TuKcY0B7SS2HLaqt8KjMq0mG0eUvzpafZAC0LhxSkxcfPJcvsBO3zOybw8DUzaLHYfWDel6G9t3MP3b+zGw/gzhzLzddEyEw5jBP5QsrACjLpHLNqdqpyH3fwVSoYoQGaewsGi/R+RqKHoVG7/ZCVFPF4xIMYH/eZXm/wdmAODUQLV2+2qfHxBZaVBZ2cW3dTpbXA8gwobJKQsjqZqewpsaiBaDmADccGIv+Eku7NWYsjivy2k2Dtvg6HaWZC+LU4Jx38YtKpUXdjQ1uhUX9Cx4KbhJh5VUCfwbi1IKuYUEYA8zJP8XfJoge2oi5P9MAQy09DuJpWlrWydC0aTAYvXKcEx3hgztM6l05HgyvseQJrwtSbVGZMxjy+/ADRq8IB5BrORrMx+Ywb61+h42z15zFb7kjGIQ0D9aGGjHbvSd9Y/uFRl9brf7PYnuLWmepp+yWYtHh+R/ZhkBgt2AO6K0/ERG2aLlbqKRkdslyiflFVpPFtV2CrrITzHw8TgtdbyyWPKsTIxUfoM3RHSRlWiwJ8+1z43ri
  template:
    metadata:
      name: backend-secret
      namespace: default
