include:
  - local: 'ci/templates/workflow.yml'
  - local: 'ci/templates/stages.yml'

  - local: 'ci/templates/base/docker-job.yml'
  - local: 'ci/templates/base/ssh-job.yml'

  - local: 'ci/templates/jobs/build.yml'
  - local: 'ci/templates/jobs/lint.yml'
  - local: 'ci/templates/jobs/test.yml'
  - local: 'ci/templates/jobs/deploy.yml'
