build-backend:
  stage: build
  extends: .docker-job

  rules:
    - changes:
      - app/backend/**/*
      - app/backend/Dockerfile
      - app/tests/**/*

  script:
    - echo "Building backend..."
    - docker build -f app/backend/Dockerfile -t "$DOCKERHUB_USER/speakflow-backend:${CI_COMMIT_SHA:-latest}" .
    - echo "Pushing the image to Docker Hub..."
    - docker push "$DOCKERHUB_USER/speakflow-backend:${CI_COMMIT_SHA:-latest}"


build-frontend:
  stage: build
  extends: .docker-job

  rules:
    - changes:
      - app/frontend/**/*
      - app/frontend/Dockerfile

  script:
    - echo "Building frontend..."
    - docker build -t "$DOCKERHUB_USER/speakflow-frontend:${CI_COMMIT_SHA:-latest}" app/frontend/
    - echo "Pushing the image to Docker Hub..."
    - docker push "$DOCKERHUB_USER/speakflow-frontend:${CI_COMMIT_SHA:-latest}"


build-tests:
  stage: build
  extends: .docker-job

  rules:
    - changes:
      - app/backend/**/*
      - app/backend/Dockerfile
      - app/tests/**/*

  script:
    - echo "Building tests..."
    - docker build -f app/tests/Dockerfile -t "$DOCKERHUB_USER/speakflow-tests:${CI_COMMIT_SHA:-latest}" .
    - echo "Pushing the image to Docker Hub..."
    - docker push "$DOCKERHUB_USER/speakflow-tests:${CI_COMMIT_SHA:-latest}"
