build-backend:
  stage: build
  extends: .docker-job

  rules:
    - changes:
      - app/backend/**/*
      - app/backend/Dockerfile

  script:
    - echo "Building backend..."
    - docker build -f app/backend/Dockerfile -t "$DOCKERHUB_USER/speakflow-backend:latest" .
    - echo "Pushing the image to Docker Hub..."
    - docker push "$DOCKERHUB_USER/speakflow-backend:latest"


build-frontend:
  stage: build
  extends: .docker-job

  rules:
    - changes:
      - app/frontend/**/*

  script:
    - echo "Building frontend..."
    - docker build -t "$DOCKERHUB_USER/speakflow-frontend:latest" app/frontend/
    - echo "Pushing the image to Docker Hub..."
    - docker push "$DOCKERHUB_USER/speakflow-frontend:latest"


build-tests:
  stage: build
  extends: .docker-job

  rules:
    - changes:
      - app/tests/**/*

  script:
    - echo "Building tests..."
    - docker build -f app/tests/Dockerfile -t "$DOCKERHUB_USER/speakflow-tests:latest" .
    - echo "Pushing the image to Docker Hub..."
    - docker push "$DOCKERHUB_USER/speakflow-tests:latest"
