---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-postgres-secret
  namespace: default
spec:
  encryptedData:
    password: AgA7D+m5SdVxj62uqS/YOMNJknn256PQY//noPqAJBDqidagrTOTwdghBIh7HgyA1RMQ2HWZhRANjURBmI0yaagrbdHeT3WQ984j3mMOgwFpnod/Faa+rAxMKPbPO9+eXXWMr5lNGNEIqzDRT0g9NL0D/T6UsvXFL7s1FjpGdDqB2axBkzjFX/cNxNirl7xVJDba4J90/jmoBwsteUccnK89RBtgcJ4K+ukjoiDRdKJg3xFNgx6Cw47xoLw229NN8urJACcnQvypPL7hUjM0YwSo1nHXQG/TGoyvjw1y1f6Qxb8Qu4Qw0arMMA+Vkkl1pxAIbydK/EO6F5hH4qSXbC6cfFnFKDvQb/Oy4yYb9igjjKkTJhNnim4gJaIClUhAGDF7Ce2N3KyA36MV/hKMFssnOEDE95gDRjY9rMUHoJUZIFo8NxfGs/2V5SPrcJsmgMIB4/q/KbA3YBcg8serYhYLVGtwg6EVSTIl8V+tYeILmjv+FMMl9naRouOz0ZTqkWOfZLXBsIicmkHP83PL4tXLvK1f9w+JVrlGCLDeMDPkf6H4lUrWiKhPEz5dtQb1i4n+QhS/wkAxkJ92xGwIWJOZOgkOumsrbS8wT1Vy60DGwQJPKDxF3SXIOqcCY2zWONT2Yqf949rXXmzFiAl8my98WEGV/sGB4lL1tmoxEVzKGm/36+pz7VkH8oOWgk5McuqdoEMt753PinFIr9RuQARVM2K6Dob/yPGlO6ymD5PFW3hG03qe4hja
    user: AgBiD4SgltwveR/SKMOffompDhwhDXZcAdSC97jyu6c2bD6aeF3K51ALWDfE/A/XQ7MLfNcAeIqd+jXyRaKkk8aw+tS5XzliACBLWv1SZDTMJIRcwcrYy3IQlQPvvZApN2IlE0QB+CXYUjcorYZZPtJTDU+dNALxdno0YEHO3bIq9E1OXDph/375BLWMTbmlWO41OZYc77zGoX+tHkRQi0riDaeqNKww98mYJOzy/UAuZDZGu2hJRKbvBSNPeUqj/hhMJdtxDKBuA+2k79toV4FAJSbza+aktu4ziJ+Y41deryS/4zQ3mjdno1zjJqHL53yKDQc0+2f94cvovQoPQQvtbbWodgAMKY8PczGUxg0tr5fEk+5Vplfb2tQ7jNKFHSkBK8MHIlA3XGPLu6na2lzkixpPVnag86j5hKxFIKU11kFZp6kQ1AiwldGt2MpEamX5BUj+uuuMarfl3S6cjfpm66HkaEoD8Qotp7Ib5dgl7vqfFyA719euW33ZCJ87cHhs3JdP+PIHBHRDsDyCq/zAPj/A8TMYIBJXA8t4PW82H0ZA9ATcPdVXiKlExRG08LRNyPYmfESotCgA/hqA1NcaLAr4ot5Id5rC8U+3VG/gWm0phOfrvKlvuRBu5JfMlq8PRiS1mzPSFy8bA0BCpROMGGHZZ78quJ9quXSCtGNuAcyqFjI28JaeR8iEuMRKHYdSFWP2zaCytNVstcQnEUV8
  template:
    metadata:
      name: app-postgres-secret
      namespace: default
