---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    password: AgAzYWDjAT/dxm++VjkKlcE+ZqfDnEVWuDoF8hWwiBtOIEUmVsxGU61w6PFjm8DYNoCGkT+cJv67uO6wGK7IgIJsMsonXUr7FSgQmMxpPEKAipIf1zA/nLENQv/DspHoIztRajufVwPJSZwOnSs8QWkGsnGH1sptYYHXPuWmTVKNjL4AQvJ4dt6IhGfObyVhG58WSOGLEBAdaWE9k6RTX7ZZa7T0/YyNPIQfv9cxu1cSbmPoFAiov5WaXmWp78dgLRfQ9QvF0uVO8G+U/ECiWrGLAKJSmUaGyvecc69aZrrFiQhnjwcrI+BE2YaHFi2Dhh572WZhJYm6AFM3Xrz9jQSP4OV6C4ek5bac9hGCbtjZlNO/En+q4jnbTCuC4e2LzhBBjBkDbrrL3MflAEdanW1LANKnamO9Zg1vqqqu742Y3awsPPH2Y2eQelnxuQqO9D6VTV6JCfnNWgiq1sfIiFNdONVOhVrfT+H80LN6jtL9g40i9voOgZ12PgvtprTW29tI2v4mnG0ybMldz78YE97xd7Uimz/gzYfmbPzUQSdnm6s0X4HNGtK95juO8OVPlwQfisbi8maMCqNyIRVYP0rVUQpA6D1RXuaKs6ZSLxj0HJLxB3nFaphLwb37yEvNbrUfRdfuoB2/NK5F1uFeeODAxTI1bgRUZj+jFmW4GS+DMOPrRtOecZjZa8lXPn49G1kZwbdW8q3rG5YhbwABjvxWUxLv3zEdcLU0IL7ERjqT4so/A1y11K0/
    user: AgCn59QxW5Wls/zs+apDb8LB6T2CXopS5FcfPJdwHn3Q4dFXTLoCRR53c7Ld3sOsWUdrPaSwY0dgyTU3cbjbVZdVVf30hKuTvW3FZzmEIOVWGNt4qFFUCm10foNGHT2IkR4sZwil/wO9fZQSFvJkaG6zp+FwwIqzIEeLmaC/inwyvDLc4J/lTKiVmwQfyTKU1Qg0yIkWm9vGTAOXiB9A+dFjL3OHYESZAMaqZFVQ7FHrzAUg91S68fVaZfwH+j94p4oQOnovpQ2Lu2QGzhbc11FExgyvonRYYpIw7vTWln1j31GAivSHxFgI/vq/+zoFhTRqAH0cneJpLAQWFelKe7JsX+e3tN9kqOFQCy6KvDxwrC67rBtU5bEBHgsYpx1XthLmmnns5kULOUr+9dyeL6QhfcY6CNfl+savjR6VwcVFP/IT57SdmFAMy6bBBbBP3sKyz5Cx4wX9KryYKmbRRxJljVGulcKhbvoSENdvbvBvFYQF5mxlQpeOL/H7xqVSh0Uks6UaEcAwTJLNC54Jxhf6n/2/5/Ry08/8Kr+kQbIuhKC9fgkXLc91oJz/SX0fhoYfbtqv6r9q/bkZ2KxxpfJP458qWXmtq0xaNr+McEG4NfCdf+8ql2Y9WJldhVV8WdLyqXp04kaXthrPMFZfF52s+GkXujvFieDUg62o8UGdAz4ItqGoRz7sq/o5mZXKzfvrH+SPsJMckbKmoEKafNyt
  template:
    metadata:
      name: postgres-secret
      namespace: default
