"""add session feedback and live correction notes

Revision ID: a76cd5ec1af4
Revises: ae9bd76b4de6
Create Date: 2026-06-23 12:31:27.091818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a76cd5ec1af4"
down_revision: Union[str, Sequence[str], None] = "ae9bd76b4de6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "live_correction_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.String(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=False),
        sa.Column("note_text", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_live_correction_notes_room_id"),
        "live_correction_notes",
        ["room_id"],
        unique=False,
    )
    op.create_table(
        "session_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.String(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_feedback_room_id"),
        "session_feedback",
        ["room_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_feedback_room_id"), table_name="session_feedback")
    op.drop_table("session_feedback")
    op.drop_index(
        op.f("ix_live_correction_notes_room_id"), table_name="live_correction_notes"
    )
    op.drop_table("live_correction_notes")
    # ### end Alembic commands ###
