"""fix note and feedback creation issues

Revision ID: ae6bf3b4b83d
Revises: a76cd5ec1af4
Create Date: 2026-06-30 09:19:41.227773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae6bf3b4b83d'
down_revision: Union[str, Sequence[str], None] = 'a76cd5ec1af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('live_correction_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_foreign_key(None, 'live_correction_notes', 'users', ['target_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'live_correction_notes', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.add_column('session_feedback', sa.Column('feedback', sa.String(), nullable=False))
    op.alter_column('session_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_foreign_key(None, 'session_feedback', 'users', ['target_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'session_feedback', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session_feedback', 'rating')
    op.drop_column('session_feedback', 'comment')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.add_column('session_feedback', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('session_feedback', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session_feedback', type_='foreignkey')
    op.drop_constraint(None, 'session_feedback', type_='foreignkey')
    op.alter_column('session_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('session_feedback', 'feedback')
    op.drop_constraint(None, 'live_correction_notes', type_='foreignkey')
    op.drop_constraint(None, 'live_correction_notes', type_='foreignkey')
    op.alter_column('live_correction_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
